apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-oyro
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-oyro
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-oyro
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-oyro
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-oyro
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ekzl-tenant/rhtap-demo-app/hacbs-test-project-oyro@sha256:a593603d21d3aa58ccb099b938975d59cae5bfd7040bd43ffa23eaaac4efaf74
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
